name: {{name.camelCase()}}
description: {{description}}

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  line_awesome_flutter: ^2.0.0
  responsive_framework: ^0.2.0
  riverpod: ^1.0.3
  skeletons: ^0.0.3

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.10

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  background_image: "assets/bg/splash.png"

flutter:
  uses-material-design: true

  # assets:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
